name: wallet_flow
description: "Plugin for adding cards to google and apple wallet."
version: 0.0.3
homepage: https://github.com/murlod1n/wallet_flow

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.murlodin.wallet_flow
        pluginClass: WalletFlowPlugin
      ios:
        pluginClass: WalletFlowPlugin


screenshots:
  - description: The Wallet Flow logo.
    path: assets/logo.png